### ISSUE TITLE
E220-900MM22s

### ISSUE THREAD

**Issue by remi206** [christianhubmann/esphome_component_sx1262#1]
Hi!

I tried running the E220-900MM22S module, but it didn't work because there is no TCXO. Can you add this setting? I still don't understand if there is a DC-DC converter or just an LDO stabilizer. If there is no DC-DC, it would be nice if you added this \ setting as well.

**Comment by christianhubmann** [comment]
Hi, I will take a look!

**Comment by christianhubmann** [comment]
Sorry for the delay. I added the settings, you can use them like this:
````
external_components:
  - source: github://christianhubmann/esphome_component_sx1262@main
    components: [ sx1262 ]

sx1262:
  ...
  tcxo_voltage: 1.6
  use_regulator_ldo: False
````
